"""
Step Detection — CNN Training Script
=====================================
Trains a 1D CNN on temporal windows of MediaPipe landmarks for
ground-contact classification at 60fps.

Input:  sliding window of N frames × 33 landmarks × 4 values (x, y, z, vis)
        per-foot framing (target vs other) for foot-agnostic learning
Output: binary (contact / no-contact) for the center frame

Uses the 60fps-downsampled labels already generated by the labeler app.

Run from the repo root:
    python step_detection/train_cnn.py
"""

import json
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR / "data"
MODELS_DIR = SCRIPT_DIR / "models"
MODELS_DIR.mkdir(exist_ok=True)
RESULTS_DIR = SCRIPT_DIR / "results"
RESULTS_DIR.mkdir(exist_ok=True)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
WINDOW_SIZE = 15          # frames of context (odd number, center = target)
TARGET_FPS = 60           # all data resampled to this
BATCH_SIZE = 32
EPOCHS = 150
LEARNING_RATE = 1e-3
RANDOM_SEED = 42
N_AUGMENT = 8             # augmented copies per original sample

# MediaPipe landmark names (33 joints) — must match train_and_compare.py
MP_LANDMARK_NAMES = [
    "nose",
    "left_eye_inner", "left_eye", "left_eye_outer",
    "right_eye_inner", "right_eye", "right_eye_outer",
    "left_ear", "right_ear",
    "mouth_left", "mouth_right",
    "left_shoulder", "right_shoulder",
    "left_elbow", "right_elbow",
    "left_wrist", "right_wrist",
    "left_pinky", "right_pinky",
    "left_index", "right_index",
    "left_thumb", "right_thumb",
    "left_hip", "right_hip",
    "left_knee", "right_knee",
    "left_ankle", "right_ankle",
    "left_heel", "right_heel",
    "left_foot_index", "right_foot_index",
]
IDX = {name: i for i, name in enumerate(MP_LANDMARK_NAMES)}

# Joints that get swapped for per-foot framing
_SWAP_PAIRS = [
    ("left_eye_inner", "right_eye_inner"),
    ("left_eye", "right_eye"),
    ("left_eye_outer", "right_eye_outer"),
    ("left_ear", "right_ear"),
    ("mouth_left", "mouth_right"),
    ("left_shoulder", "right_shoulder"),
    ("left_elbow", "right_elbow"),
    ("left_wrist", "right_wrist"),
    ("left_pinky", "right_pinky"),
    ("left_index", "right_index"),
    ("left_thumb", "right_thumb"),
    ("left_hip", "right_hip"),
    ("left_knee", "right_knee"),
    ("left_ankle", "right_ankle"),
    ("left_heel", "right_heel"),
    ("left_foot_index", "right_foot_index"),
]


# ===========================================================================
# Data loading
# ===========================================================================

def _landmarks_to_array(lm_list: list) -> np.ndarray:
    """Convert a single frame's 33-landmark list to (33, 4) array."""
    arr = np.zeros((33, 4), dtype=np.float32)
    for i, joint in enumerate(lm_list):
        arr[i] = [joint["x"], joint["y"], joint["z"], joint["visibility"]]
    return arr


def _swap_sides(frame_arr: np.ndarray) -> np.ndarray:
    """Mirror left/right joints for per-foot framing.

    When target_side is 'right', we swap left↔right joints so the model
    always sees the target foot in the 'left' joint positions.
    """
    swapped = frame_arr.copy()
    for left_name, right_name in _SWAP_PAIRS:
        li, ri = IDX[left_name], IDX[right_name]
        swapped[li], swapped[ri] = frame_arr[ri].copy(), frame_arr[li].copy()
    return swapped


def _get_60fps_frame_mapping(original_fps: float) -> dict:
    """Map 60fps frame indices to original landmark frame indices.

    The labels_60fps.csv has frames numbered at 60fps. We need to find
    the closest original landmark frame for each.
    """
    ratio = original_fps / TARGET_FPS
    return ratio


def load_all_data():
    """Load all labeled videos and build windowed samples at 60fps.

    Returns:
        X: np.ndarray of shape (N, WINDOW_SIZE, 33, 4)
        y: np.ndarray of shape (N,) with 0/1 labels
        groups: np.ndarray of shape (N,) with video index for each sample
    """
    all_X = []
    all_y = []
    all_groups = []

    for video_idx, video_dir in enumerate(sorted(DATA_DIR.iterdir())):
        if not video_dir.is_dir():
            continue
        labels_60_path = video_dir / "labels_60fps.csv"
        landmarks_path = video_dir / "landmarks.json"
        metadata_path = video_dir / "metadata.json"

        if not labels_60_path.exists() or not landmarks_path.exists():
            print(f"  ⚠ Skipping {video_dir.name}: missing files")
            continue

        with open(metadata_path, "r") as f:
            meta = json.load(f)
        original_fps = meta["fps"]

        # Load landmarks (keyed by original frame index)
        with open(landmarks_path, "r") as f:
            landmarks_raw = json.load(f)

        # Convert to sorted array of (original_frame, landmark_array)
        orig_frames = sorted(landmarks_raw.keys(), key=int)
        orig_frame_ints = [int(f) for f in orig_frames]
        landmark_arrays = {int(f): _landmarks_to_array(landmarks_raw[f]) for f in orig_frames}

        # Load 60fps labels
        labels_df = pd.read_csv(labels_60_path)

        # Build contact lookup at 60fps frame indices
        # The 60fps labels have their own frame column — map each to nearest original frame
        ratio = original_fps / TARGET_FPS
        contact_60fps = {}  # 60fps_frame -> set of sides
        for _, row in labels_df.iterrows():
            fr60 = int(row["frame"])
            contact_60fps.setdefault(fr60, set()).add(row["side"])

        # Build the sequence of landmark arrays at 60fps
        # For each 60fps frame, find nearest original landmark frame
        min_orig = min(orig_frame_ints)
        max_orig = max(orig_frame_ints)
        min_60 = int(min_orig / ratio)
        max_60 = int(max_orig / ratio)

        # Build dense 60fps landmark sequence
        seq_length = max_60 - min_60 + 1
        landmark_seq = np.zeros((seq_length, 33, 4), dtype=np.float32)

        for i in range(seq_length):
            fr60 = min_60 + i
            # Map to nearest original frame
            orig_fr = round(fr60 * ratio)
            # Find closest available original frame
            closest = min(orig_frame_ints, key=lambda x: abs(x - orig_fr))
            if abs(closest - orig_fr) <= 2:  # within 2 frames tolerance
                landmark_seq[i] = landmark_arrays[closest]

        # Build contact label array at 60fps
        label_seq = np.zeros(seq_length, dtype=np.int32)
        label_sides = [set() for _ in range(seq_length)]
        for fr60, sides in contact_60fps.items():
            idx = fr60 - min_60
            if 0 <= idx < seq_length:
                label_sides[idx] = sides

        # Generate windowed samples with per-foot framing
        half = WINDOW_SIZE // 2
        n_pos = 0
        n_neg = 0

        for center in range(half, seq_length - half):
            window = landmark_seq[center - half: center + half + 1]  # (WINDOW_SIZE, 33, 4)

            # Skip if center frame has no landmark data (all zeros)
            if np.sum(np.abs(window[half])) < 0.01:
                continue

            sides_contacting = label_sides[center]

            for target_side in ("left", "right"):
                # Per-foot framing: if target is right, swap left↔right
                if target_side == "right":
                    w = np.stack([_swap_sides(window[t]) for t in range(WINDOW_SIZE)])
                else:
                    w = window.copy()

                is_contact = 1 if target_side in sides_contacting else 0
                all_X.append(w)
                all_y.append(is_contact)
                all_groups.append(video_idx)

                if is_contact:
                    n_pos += 1
                else:
                    n_neg += 1

        print(f"  {video_dir.name:20s} -- {n_pos:4d} contact, {n_neg:4d} non-contact  "
              f"(fps={original_fps:.0f}, 60fps frames={seq_length})")

    X = np.array(all_X, dtype=np.float32)  # (N, WINDOW_SIZE, 33, 4)
    y = np.array(all_y, dtype=np.int32)
    groups = np.array(all_groups, dtype=np.int32)

    print(f"\n  Total: {len(X)} samples, {y.sum()} contact, {len(y) - y.sum()} non-contact")
    return X, y, groups


# ===========================================================================
# CNN Model
# ===========================================================================

def augment_batch(X, y, n_augment=N_AUGMENT):
    """Create augmented copies of training data.

    Augmentations:
      - Coordinate jitter: small gaussian noise on x/y/z (not visibility)
      - Temporal shift: shift window by ±1-2 frames (roll along time axis)
      - Horizontal flip: mirror x coordinates (1 - x)
    """
    aug_X = [X]
    aug_y = [y]

    rng = np.random.RandomState(RANDOM_SEED)

    for i in range(n_augment):
        X_new = X.copy()

        # Coordinate jitter (small noise on x,y,z — not visibility channel 3)
        noise_scale = 0.005 + rng.random() * 0.01  # 0.005 to 0.015
        noise = rng.randn(*X_new.shape).astype(np.float32) * noise_scale
        noise[:, :, :, 3] = 0  # don't add noise to visibility
        X_new = X_new + noise

        # Temporal shift (roll ±1 or ±2 frames along time axis)
        shift = rng.randint(-2, 3)  # -2, -1, 0, 1, 2
        if shift != 0:
            X_new = np.roll(X_new, shift, axis=1)

        # Horizontal flip (50% chance): mirror x coordinates
        if rng.random() > 0.5:
            X_new[:, :, :, 0] = 1.0 - X_new[:, :, :, 0]  # flip x

        aug_X.append(X_new)
        aug_y.append(y)

    return np.concatenate(aug_X), np.concatenate(aug_y)


def build_cnn_model(input_shape):
    """Build a compact 1D CNN for temporal landmark classification.

    Input shape: (WINDOW_SIZE, 33 * 4) = (15, 132)
    Output: single sigmoid (contact probability)

    Kept small (~18K params) to avoid overfitting on limited data.
    """
    import torch
    import torch.nn as nn

    class StepCNN(nn.Module):
        def __init__(self):
            super().__init__()
            n_features = input_shape[1]  # 132

            self.features = nn.Sequential(
                nn.Conv1d(n_features, 32, kernel_size=3, padding=1),
                nn.BatchNorm1d(32),
                nn.ReLU(),
                nn.Dropout(0.3),

                nn.Conv1d(32, 32, kernel_size=3, padding=1),
                nn.BatchNorm1d(32),
                nn.ReLU(),
                nn.AdaptiveAvgPool1d(4),  # compress time to 4 bins
            )

            self.classifier = nn.Sequential(
                nn.Flatten(),
                nn.Linear(32 * 4, 32),
                nn.ReLU(),
                nn.Dropout(0.4),
                nn.Linear(32, 1),
            )

        def forward(self, x):
            # x: (batch, window_size, features)
            x = x.permute(0, 2, 1)  # (batch, features, window_size)
            x = self.features(x)
            x = self.classifier(x)
            return x.squeeze(-1)

    return StepCNN()


# ===========================================================================
# Training
# ===========================================================================

def train():
    import torch
    import torch.nn as nn
    from torch.utils.data import TensorDataset, DataLoader

    print("=" * 60)
    print("Step Detection CNN -- Training on 60fps Data")
    print("=" * 60)
    print(f"Window size: {WINDOW_SIZE} frames ({WINDOW_SIZE / TARGET_FPS:.3f}s)")
    print(f"Target FPS: {TARGET_FPS}")
    print(f"Augmentation: {N_AUGMENT}x copies per sample")
    print()

    # Load data
    print("Loading data...")
    X_raw, y_raw, groups = load_all_data()

    # Leave-one-video-out split for validation (before augmentation)
    np.random.seed(RANDOM_SEED)
    unique_groups = np.unique(groups)
    val_group = np.random.choice(unique_groups)

    train_mask = groups != val_group
    val_mask = groups == val_group

    X_train_raw, y_train_raw = X_raw[train_mask], y_raw[train_mask]
    X_val_raw, y_val_raw = X_raw[val_mask], y_raw[val_mask]

    # Augment training data only
    print(f"\nAugmenting training data ({N_AUGMENT}x)...")
    X_train_aug, y_train_aug = augment_batch(X_train_raw, y_train_raw, N_AUGMENT)

    # Reshape: (N, WINDOW_SIZE, 33, 4) -> (N, WINDOW_SIZE, 132)
    X_train = X_train_aug.reshape(len(X_train_aug), WINDOW_SIZE, -1)
    X_val = X_val_raw.reshape(len(X_val_raw), WINDOW_SIZE, -1)

    print(f"Train: {len(X_train)} samples ({len(X_train_raw)} original + augmented)")
    print(f"Val: {len(X_val)} samples (video group {val_group})")
    print(f"Class balance (train): {y_train_aug.sum()}/{len(y_train_aug)} positive "
          f"({100 * y_train_aug.sum() / len(y_train_aug):.1f}%)")

    # Normalize: compute mean/std from original training data (not augmented)
    X_train_orig_flat = X_train_raw.reshape(len(X_train_raw), WINDOW_SIZE, -1)
    train_mean = X_train_orig_flat.mean(axis=0, keepdims=True)
    train_std = X_train_orig_flat.std(axis=0, keepdims=True) + 1e-8
    X_train = (X_train - train_mean) / train_std
    X_val = (X_val - train_mean) / train_std

    y_train = y_train_aug
    y_val = y_val_raw

    # Class weights for imbalanced data
    n_pos = y_train.sum()
    n_neg = len(y_train) - n_pos
    pos_weight = torch.tensor([n_neg / max(n_pos, 1)], dtype=torch.float32)
    print(f"Positive weight: {pos_weight.item():.2f}")

    # Build datasets
    train_ds = TensorDataset(
        torch.from_numpy(X_train),
        torch.from_numpy(y_train.astype(np.float32)),
    )
    val_ds = TensorDataset(
        torch.from_numpy(X_val),
        torch.from_numpy(y_val.astype(np.float32)),
    )
    train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_dl = DataLoader(val_ds, batch_size=BATCH_SIZE)

    # Build model
    model = build_cnn_model(input_shape=(WINDOW_SIZE, 132))
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, patience=10, factor=0.5)

    param_count = sum(p.numel() for p in model.parameters())
    print(f"\nModel parameters: {param_count:,}")
    print(model)
    print()

    # Training loop
    best_val_f1 = 0
    best_epoch = 0
    patience_counter = 0
    patience = 20

    for epoch in range(EPOCHS):
        # Train
        model.train()
        train_loss = 0
        train_correct = 0
        train_total = 0

        for xb, yb in train_dl:
            optimizer.zero_grad()
            logits = model(xb)
            loss = criterion(logits, yb)
            loss.backward()
            optimizer.step()

            train_loss += loss.item() * len(xb)
            preds = (torch.sigmoid(logits) > 0.5).float()
            train_correct += (preds == yb).sum().item()
            train_total += len(yb)

        train_loss /= train_total
        train_acc = train_correct / train_total

        # Validate
        model.eval()
        val_loss = 0
        val_preds_all = []
        val_labels_all = []

        with torch.no_grad():
            for xb, yb in val_dl:
                logits = model(xb)
                loss = criterion(logits, yb)
                val_loss += loss.item() * len(xb)
                preds = (torch.sigmoid(logits) > 0.5).float()
                val_preds_all.extend(preds.numpy())
                val_labels_all.extend(yb.numpy())

        val_loss /= len(val_ds)
        val_preds_arr = np.array(val_preds_all)
        val_labels_arr = np.array(val_labels_all)
        val_acc = (val_preds_arr == val_labels_arr).mean()

        # F1
        tp = ((val_preds_arr == 1) & (val_labels_arr == 1)).sum()
        fp = ((val_preds_arr == 1) & (val_labels_arr == 0)).sum()
        fn = ((val_preds_arr == 0) & (val_labels_arr == 1)).sum()
        precision = tp / max(tp + fp, 1)
        recall = tp / max(tp + fn, 1)
        val_f1 = 2 * precision * recall / max(precision + recall, 1e-8)

        scheduler.step(val_loss)

        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f"  Epoch {epoch + 1:3d}/{EPOCHS} — "
                  f"train_loss={train_loss:.4f} train_acc={train_acc:.4f} | "
                  f"val_loss={val_loss:.4f} val_acc={val_acc:.4f} val_f1={val_f1:.4f}")

        # Early stopping on F1
        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            best_epoch = epoch + 1
            patience_counter = 0
            # Save best model
            torch.save({
                'model_state_dict': model.state_dict(),
                'train_mean': train_mean,
                'train_std': train_std,
                'window_size': WINDOW_SIZE,
                'input_features': 132,
                'target_fps': TARGET_FPS,
                'best_f1': best_val_f1,
                'epoch': best_epoch,
            }, str(MODELS_DIR / "step_cnn.pt"))
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"\n  Early stopping at epoch {epoch + 1}")
                break

    print(f"\n  Best val F1: {best_val_f1:.4f} at epoch {best_epoch}")
    print(f"  Model saved to: {MODELS_DIR / 'step_cnn.pt'}")

    # Final evaluation on validation set with best model
    checkpoint = torch.load(str(MODELS_DIR / "step_cnn.pt"), weights_only=False)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()

    val_preds_all = []
    val_probs_all = []
    val_labels_all = []

    with torch.no_grad():
        for xb, yb in val_dl:
            logits = model(xb)
            probs = torch.sigmoid(logits)
            preds = (probs > 0.5).float()
            val_preds_all.extend(preds.numpy())
            val_probs_all.extend(probs.numpy())
            val_labels_all.extend(yb.numpy())

    val_preds_arr = np.array(val_preds_all)
    val_labels_arr = np.array(val_labels_all)

    tp = ((val_preds_arr == 1) & (val_labels_arr == 1)).sum()
    fp = ((val_preds_arr == 1) & (val_labels_arr == 0)).sum()
    fn = ((val_preds_arr == 0) & (val_labels_arr == 1)).sum()
    tn = ((val_preds_arr == 0) & (val_labels_arr == 0)).sum()

    print(f"\n  Final Results:")
    print(f"    TP={tp}  FP={fp}  FN={fn}  TN={tn}")
    print(f"    Precision: {tp / max(tp + fp, 1):.4f}")
    print(f"    Recall:    {tp / max(tp + fn, 1):.4f}")
    print(f"    F1:        {2 * tp / max(2 * tp + fp + fn, 1):.4f}")
    print(f"    Accuracy:  {(tp + tn) / max(tp + tn + fp + fn, 1):.4f}")


if __name__ == "__main__":
    train()
